### ISSUE TITLE
How to get the testing results for Spring, Summer, Fall, and Winter

### ISSUE THREAD

**Issue by DongChen06** [cjdjr/T-MAAC#2]
Dear authors, I am wondering how to get the results in Table 1 via test.py for different seasons. Thank you so much!
![image](https://user-images.githubusercontent.com/25771207/195594483-4db94b75-fe09-4994-9f6b-9c304c8e70d2.png)

**Comment by cjdjr** [comment]
Thanks for your interest in our work!
We evaluate algorithms in different episodes (see test_data.csv). This test dataset consists of four parts: Spring (Mar., Apr.,
May.), Summer (Jun., Jul., Aug.), Fall (Sept., Oct., Nov.), Winter (Dec.,Jan., Feb). The test results of different months in the same season are averaged and reported.

**Comment by DongChen06** [comment]
Thanks for your quick reply! The information is really helpful. 

Just want to confirm that if I want to get the stats for month#1, then I can just enter the day_id one by one to get the stats?
![image](https://user-images.githubusercontent.com/25771207/195599141-a7ca1488-a3e7-4da5-a699-1bf391b8ae97.png)

**Comment by cjdjr** [comment]
> 

You can run the code just like this:
python test.py --save-path trial/model_save --alg icstransmaddpg --alias example_0 --scenario case141_3min_final --qweight 0.01 --voltage-barrier-type l2 **--test-mode test_data**

Then you can get results of each episode.
